#### 1. Longest Common Subsequence
#### 2. Chain Matrix Multiplication
#### 3. Text Justification
#### 4. Your Choice of Problem (not Fibanacci nor edit distance)

#### Straight forward brute-force Approach
#### Dictinary-based Approach
#### Array-based Approach

#### 1. Longest Common Subsequence

In [18]:
import numpy as np
def LCS_brute(x,y):
    if (len(x) == 0 or len(y) == 0):
        return 0
    elif (x[-1] == y[-1]):
        print (x[-1])
        return 1 + LCS_brute(x[:-1],y[:-1])
    else:
        return max(LCS_brute(x[:-1],y),LCS_brute(x,y[:-1]))
            
                
    
def LCS_dis(x,y,d):
    key = str(len(x))+"-"+str(len(y))
    if (key in d):
        return d[key]
    elif (len(x)==0 or len(y)==0):
        d[key]=0
        return d[key]
    elif (x[0]==y[0]):
        ans = 1 + LCS_dis(x[1:],y[1:],d)
        d[key] = ans
        return d[key]
    else:
        ans = max(LCS_dis(x[1:],y,d),LCS_dis(x,y[1:],d))
        d[key] = ans
        return d[key]
        
    

def LCS_array(x,y):
    num_r = len(x)+1
    num_c = len(y)+1
    a = np.zeros((num_r, num_c), dtype=int)
    for r in range(1, num_r):
        for c in range(1, num_c):
            if x[r-1] == y[c-1]:
                a[r, c] = a[r-1, c-1] + 1
            else:
                a[r, c] = max(a[r-1, c], a[r, c-1])
    print (a)
    return a[-1, -1]
a = "ASDFGHJKLZXCVBNM"
b = "ZXCVBNMASDFGHJKL"
a = "NTHU"
b = "NCTU"

d = {}
LCS_dis(a,b,d)
LCS_brute(a,b)
LCS_array(a,b)
print (d)

U
T
N
N
N
N
[[0 0 0 0 0]
 [0 1 1 1 1]
 [0 1 1 2 2]
 [0 1 1 2 2]
 [0 1 1 2 3]]
{'0-3': 0, '0-2': 0, '0-0': 0, '1-1': 1, '1-2': 1, '1-3': 1, '2-0': 0, '2-1': 1, '2-2': 1, '2-3': 1, '3-2': 2, '3-3': 2, '4-4': 3}


#### 2. Chain Matrix Multiplication

In [29]:
import sys
def MCM_brute(chain):
    if len(chain) <= 1: 
        return 0
    _min = sys.maxsize 
    for k in range(1,len(chain)):
        count = (MCM_brute(chain[:k])  
             + MCM_brute(chain[k:]) 
                   + chain[0][0] * chain[k-1][1] * chain[-1][1]) 
        if count < _min: 
            _min = count
    return _min
                
    
def MCM_dis(chain):
    n=len(chain)
    a = {}
    for i in range(n):
        for j in range(n):
            a[str(i)+"-"+str(j)] = 0
    for length in range(2, n):     
        for i in range(1, n - length + 1):
            j = i + length - 1
            a[str(i)+"-"+str(j)] = sys.maxsize
            for k in range(i, j):   
                count = a[str(i)+"-"+str(k)] + a[str(k+1)+"-"+str(j)] + chain[i-1]*chain[k]*chain[j]
                if(count < a[str(i)+"-"+str(j)]):    
                    a[str(i)+"-"+str(j)] = count
    return  a[str(i)+"-"+str(j)] 
    
    

def MCM_array(chain):
    n=len(chain)
    m = [ [ 0 for i in range(n) ] for i in range(n) ]
    
    for i in range(1, n):     
        m[i][i] = 0
        
    for length in range(2, n):     
        for i in range(1, n - length + 1):
            j = i + length - 1
            m[i][j] = sys.maxsize
            for k in range(i, j):   
                count = m[i][k] + m[k+1][j] + chain[i-1]*chain[k]*chain[j]
                if(count < m[i][j]):    
                    m[i][j] = count
    return m[1][n-1]

ch = [(1,10),(10,1),(1,5)]
print (MCM_brute(ch))
ch = [1,10,1,5]
MCM_dis(ch)

15


15

#### 3. Text Justification

In [40]:

def TJ_brute(tl,lw):
    if (len(tl) == 0):
        return 0
    elif (len(tl) == 1):
        return (lw - len(tl[0]))**2
    else:
        usage = len(tl[0])
        waste = [(lw - usage)**2]
        maxwords = 1
        while (not maxwords == len(tl)  and  usage + 1 + len(tl[maxwords]) <= lw):
            usage += 1 + len(tl[maxwords])
            waste.append((lw - usage)**2)
            maxwords += 1
            
    return min(waste[i] + TJ_brute(tl[i+1:],lw) for i in range(maxwords))
    
def TJ_dis(tl,lw,d,i,j):
    key = str(i) + "-" + str(j)
    if key in d:
        return d[key]
    print(key)
    if i > j:
        d[key] = 0
        return d[key]
    elif i == j:
        d[key] = (lw - len(tl[0])) ** 2
        return d[key]  # '''if lineWidth < text, won't be captured'''
    else:
        usage = 0
        waste = 0
        maxwords = 0
        
        while (i + maxwords <= j and
               usage + len(tl[i + maxwords]) <= lw):  # 排得下才來排
            if usage == 0:
                usage = len(tl[i])
                waste = [(lw-usage)**2]
                maxwords = 1
            else:
                usage = usage + 1 + len(tl[i + maxwords])  # 不能只有放字, 還要空格
                waste.append((lw-usage)**2)
                maxwords += 1  # 前進一個字
        
        d[key] = min([waste[k] + TJ_dis(tl, lw, d, i+k+1, j) for k in range(maxwords)])
        return d[key]
        

def usage(wl, start, end):
    word_use = 0
    for i in range(start, end+1):
        word_use += len(wl[i])
    word_use += end - start
    return word_use

def TJ_array(tl, lw):
    N = len(tl) 
    sol_list = [-99999 for i in range(N)]
    sol_list.append(0)
    for i in range(N-1, -1, -1):    
        j = i
        curr_cost = 0
        min_cost = 99999
        while (j <= N-1 and usage(tl, i, j) <= lw):
            curr_cost = (lw-usage(tl, i, j))**2 + sol_list[j+1]
            if curr_cost < min_cost:
                min_cost = curr_cost
            j += 1      # for a space after a word
            sol_list[i] = min_cost
    for i in range(0, N-1):
        if(sol_list[i] <= sol_list[i+1]):
            print(tl[i], end=" ")
        else:
            print(tl[i])
    print(tl[N-1])
    return sol_list

d = {}
t = 'It was the worst of time. It was the best of time.'
textList = t.split()
TJ_brute(textList,20)
TJ_dis(textList,20,d,0,len(textList)-1)
TJ_array(textList,20)

0-11
1-11
2-11
3-11
4-11
5-11
6-11
7-11
8-11
9-11
10-11
11-11
12-11
It was the worst
of time. It was
the best of time.


[50, 81, 129, 185, 34, 65, 149, 208, 9, 49, 144, 225, 0]

#### 4. Knapsack Problem

In [53]:
def KP_brute(n,w):
    length = len(n)
    if (length == 0 or w == 0):
        return 0
    if (n[0][0] > w):
        return KP_brute(n[1:],w)
    else:
        return max(KP_brute(n[1:],w-n[0][0]) + n[0][1] ,KP_brute(n[1:],w))
    

def KP_dis(n,w,b,pre_key):
    length = len(n)
    if (length == 0 or w ==0):
        return 0
    key = str(n[0]) + "-" + pre_key
    if (key in b):
        return b[key]
    elif (n[0][0] > w):
        return KP_dis(n[1:],w,b,key)
    else:
        b[key] = max(KP_dis(n[1:],w-n[0][0],b,key) + n[0][1]
                                  ,KP_dis(n[1:],w,b,key))
        return b[key]
    

def KP_array(n,w,a):
    length = len(n)
    if (a[length][w] and a[length][w] != 0):
        return a[length][w]
    if (length == 0 or w == 0):
        return 0
    if (n[0][0] > w):
        return KP_array(n[1:],w,a)
    else:
        a[length][w] = max(KP_array(n[1:],w-n[0][0],a) + n[0][1]
                                  ,KP_array(n[1:],w,a))
        return a[length][w]

item = [(4,4500),(5,5700),(2,2250),(1,1100),(6,6700)] 
weight = 8
b = {}
#print (KP_brute(item,8))
#a = [[0 for i in range((weight+1)) ] for i in range((len(item)+1))]
KP_dis(item,weight,b,"")
print(b)

{'(1, 1100)-(2, 2250)-(5, 5700)-(4, 4500)-': 1100, '(2, 2250)-(5, 5700)-(4, 4500)-': 3350, '(5, 5700)-(4, 4500)-': 9050, '(4, 4500)-': 9050}
